### ISSUE TITLE
Windows Taskbar always appears

### ISSUE THREAD

**Issue by StevensND** [baffler/Transparent-Twitch-Chat-Overlay#16] opened 2018-12-13 17:42 UTC
Hi,

Everytime I open the program and start a game in borderless mode I always get the windows taskbar annoying me and I don't know how to hide it.

It's something like this:

http://prntscr.com/lukzv1

**Comment by StevensxD** [comment] 2018-12-22 09:15
Any help?

**Comment by baffler** [comment] 2018-12-23 15:56
Is it only happening with the program running (didn't see the program in the screenshot)? Is it also messing up for every game? Just need more info to reproduce the issue cause I'm never getting this happen. Maybe a workaround you can try, right click the taskbar then click Taskbar Settings, then turn on Automatically hide the taskbar in desktop mode. You can put your mouse at the bottom of the screen to see the taskbar, but it will autohide now.

**Comment by We-Who-Belong** [comment] 2019-01-05 01:40
I'm having this same issue regardless of game despite having Auto-hide enabled. 
(Age of Wonders 3, League of Legends, Starcraft 2 were my test cases)
1. Open game in fullscreen (borderless)
2. Run program
3. Observe that scrolling to the bottom of the screen causes the task bar to pop back up.

**Comment by AHNS** [comment] 2019-05-24 16:56
I'm having this same issue while playing almost every game.
Autohiding the taskbar makes few other problems.

I used to use a program named "Restream Chat".
Icon of that program only appears on the system tray of the taskbar, not on the actual taskbar.
You should consider this feature.

**Comment by baffler** [comment] 2020-07-21 04:21
I do think hiding the taskbar icon should fix this. I didn't get to add that in v0.7 but it will be in the next version for sure. I plan on doing v0.7.1 soon since there might be a few bugs or issues with v0.7 since I made quite a few changes.

**Comment by baffler** [comment] 2020-10-01 00:57
Can you see if [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) fixes this issue? It will let you hide the icon in the taskbar now.

**Comment by We-Who-Belong** [comment] 2020-10-04 17:45
Can't replicate anymore on this end!

**Closed** 2023-10-15 05:42 UTC
Labels: question
